version: '3.1'

services:

  db:
    image: library/postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432


